### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ldeluigi** [SpaceCowMedia/commander-spellbook-backend#227]
- [x] Update variants on cards update
- [x] In generation, update identity, prices and legalities of variants
- [x] Update variants playable fields on card manual change
- [x] Add query syntax for prices and legalities
